[project]
name = "ophishal"
version = "0.1.0"
description = "Context and pretext modeling using GenAI for phishing campaign during red team engagements"
authors = [
    {name = "ropbear",email = "github@selfhosted.systems"}
]
license = {text = "GPL-3.0-or-later"}
readme = "README.md"
requires-python = ">=3.10"


[tool.poetry]
packages = [
  { include = "ophishal" }
]

[tool.poetry.scripts]
ophishal = "ophishal.cli:main"


[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"

[tool.poetry.dependencies]
jinja2 = "^3.1"
python-magic = "^0.4.27"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
